function makemap(cdata1)
%CREATEFIGURE(CDATA1)
%  CDATA1:  image cdata

%  Auto-generated by MATLAB on 06-Nov-2018 15:22:42

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create image
image([11 12 13 14 15 16],[1 100],cdata1,'Parent',axes1,...
    'CDataMapping','scaled');

% Create xlabel
xlabel('window sample size');

% Create title
title('Speedup Factor Over Window Size and UPR Length');

% Create ylabel
ylabel('UPR Length as a Percentage of N');

% Uncomment the following line to preserve the X-limits of the axes
xlim(axes1,[10.5 16.5]);
% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes1,[0 100]);
% Create colorbar
c = colorbar('peer',axes1);
c.Label.String = 'Speedup Factor in dB';

ytickformat('{%2d}\%')
xtickformat('2^{%2d}')